language: go
go:
- 1.8.x
services:
- mongodb
before_install:
- wget https://s3.amazonaws.com/sico-ops/config.travis.json -O controller/config.json
install:
- go get -t ./...
script: go test -test.bench=".*" -v ./controller/...
notifications:
  slack:
    secure: l07iRSVW6asBELgBCsUODZz1Lo/RuxSrpb1y2nCVo2WdVIKzkSmjOHotmOhN3uFNcEfoZjnxHKvrB7C3SDujmrrGaI7G4PRt/oWQlXGcaziOUS72QUd/1iYERKXnSe59/pAxRNFdLXx2x23Bx1hyyF0fk0CxqM3P/hlu9EymqPaS/+yAeivhyAWffVwAyZbNd1hlipNxJwolnqOn8xG9bSuIDU/0wFg14nYHeaen4aaUC6nuyPRT9T2xI0Zkgrv3gvMCVjkTzNR5xDATo1bziraV17fEOU3/8GHEDswZWnOvfqzJbShERRQgxpUBIWZB9TOsROl5tkjhN+aK69t05qvX8YHA5Tktow7Q85NsyG9M37LwvN0Fxyl0zuUL7h3WpRSqEIMQtAgiPMPPBvpgiUO6h0kJL8qjSSXLk8ilPh6N9z2fC1dBa/JC11MTUJjmNVTUCf4xfzG0AMsEX6KQW1vujpAB/llrcnrxuVttl5no8uzAkAOXYReUdYmz3M5Jr7JChZNXU8gICDLBhjvL8B+2hnHcfp1FPPwiGiaqAyPIA5xMV2PIWzyvIpdnPEgu/LgDIa9oemiYk+gPSfSrhk0R8/aFo7YH1+9pwIFmlpUVIBICsJnAL2nIi9zf5Xl6v09+jPpc7/ElsDXySqVuS9FN5c6xrGQ37LYmGLFAUA4=
  webhooks:
    urls:
      secure: I42twChp5vUVA7rSJCH5Mdwt9neFNa2BQhPPBmX5w+8XpOWho6ZXQStLkKzO1uJ22TDPXu7nBGLfPpcuAOkO45V7pnedmiR0aumvDNU6DnFp8DLI8ksahBG+q4czA+loH7beVKyKHgnbjxt1cRdT6VrDyZjUXwvUVy33CrgZjSA4wEDIMefcW+9aGIR8MDhJBNV1Cv5BKkEm5AiLIY/K0vrZRQfpjANJZMpCtqIggIF+CTPZC2lRideKBPCFBUaFZHzvLKOO63PRD7pbiX4U/rvguFRcquLx0XcLZ0a2lHuUgSoZkNgFlM/9rPWuOmcF0nTzTetaAQDAQVjqIN2RKCPaLYXwR7vv9EpecxUxuzKOqgolh+2ttIcXQ4pSKlhZuoQ0cqn5K30o/iG2edTfUictN1K7nYpEHppQY3d0D6INJzJGRiEAvA7HsrL4LkrstWAPPnSPb6w6kDZainRrOz19sq1lzgSm92rd/346jFXlzNT1sv6TRUH0ZNUn6B9KUyZ5oUORGoiaKkyOrxapivLHOx9JHNYqk7SGJ3x5Hzat23qzNTx9UyLQXBqo5te6eqlcrFAZ+TFx4WojPFgzOGTwoTSjfwOWDk7VUfjI1ypF2l2ik3mOdW+QM+rDsLotoYxE+yibOUO4ElOp2kGdwcd0MXxTR3hHacVtVaoZCjo=
